version: '3.8'

services:
    php:
        build:
            context: .
            target: php
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
        ports:
            - "8000:8080"
        depends_on:
            - database
            - redis

    database:
        image: mysql:8.1
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

    redis:
        image: redis:alpine
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"

volumes:
    db-data: ~
